# Generated by Django 5.2.4 on 2025-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
