# Generated by Django 5.2.4 on 2025-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothingitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(choices=[('T-paita', 'T-paita'), ('Huppari', 'Huppari'), ('Kauluspaita', 'Kauluspaita'), ('Knit', 'Knit'), ('Farkut', 'Farkut'), ('Shortsit', 'Shortsit'), ('Hame', 'Hame'), ('Puvun housut', 'Puvun housut'), ('Coach jacket', 'Coach jacket'), ('Bomber', 'Bomber'), ('Bleiseri', 'Bleiseri'), ('Tennarit', 'Tennarit'), ('Saappaat', 'Saappaat'), ('Sandaalit', 'Sandaalit'), ('Laukku', 'Laukku'), ('Vyö', 'Vyö'), ('Lippis', 'Lippis'), ('Kaulakoru', 'Kaulakoru'), ('Muu vaate', 'Muu vaate')], default='Muu vaate', max_length=50),
        ),
    ]
