# Generated by Django 5.2.4 on 2025-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_clothingitem_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
