# Generated by Django 5.2.4 on 2025-08-11 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_clothingitem_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='last_wore',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(choices=[('T-paita', 'T-paita'), ('Huppari', 'Huppari'), ('Kauluspaita', 'Kauluspaita'), ('Knit', 'Knit'), ('Svetari', 'Svetari'), ('Farkut', 'Farkut'), ('Cargohousut', 'Cargohousut'), ('Shortsit', 'Shortsit'), ('Hame', 'Hame'), ('Puvun housut', 'Puvun housut'), ('Coach jacket', 'Coach jacket'), ('Bomber', 'Bomber'), ('Bleiseri', 'Bleiseri'), ('Tennarit', 'Tennarit'), ('Saappaat', 'Saappaat'), ('Sandaalit', 'Sandaalit'), ('Laukku', 'Laukku'), ('Vyö', 'Vyö'), ('Lippis', 'Lippis'), ('Kaulakoru', 'Kaulakoru'), ('Muu vaate', 'Muu vaate')], default='Muu vaate', max_length=50),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('other', 'Other')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('worn_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_outfit_item', to='clothes.clothingitem')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_items', to='clothes.outfit')),
            ],
            options={
                'ordering': ['slot', 'position'],
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(related_name='outfits', through='clothes.OutfitItem', to='clothes.clothingitem'),
        ),
        migrations.AddConstraint(
            model_name='outfititem',
            constraint=models.UniqueConstraint(condition=models.Q(('slot__in', ['accessory', 'other']), _negated=True), fields=('outfit', 'slot'), name='uniq_single_slot_per_outfit'),
        ),
    ]
