# Generated by Django 5.2.4 on 2025-08-31 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_clothingitem_last_wore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(choices=[('T-paita', 'T-paita'), ('Huppari', 'Huppari'), ('Kauluspaita', 'Kauluspaita'), ('Knit', 'Knit'), ('Svetari', 'Svetari'), ('Toppi', 'Toppi'), ('Polo', 'Polo'), ('Farkut', 'Farkut'), ('Cargohousut', 'Cargohousut'), ('Shortsit', 'Shortsit'), ('Hame', 'Hame'), ('Chinot', 'Chinot'), ('Collegehousut', 'Collegehousut'), ('Puvun housut', 'Puvun housut'), ('Housut', 'Housut'), ('Coach jacket', 'Coach jacket'), ('Bomber', 'Bomber'), ('Bleiseri', 'Bleiseri'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Varsity jacket', 'Varsity jacket'), ('Puffer jacket', 'Puffer jacket'), ('Trench coat', 'Trench coat'), ('Denim jacket', 'Denim jacket'), ('Tennarit', 'Tennarit'), ('Boots', 'Boots'), ('Loafers', 'Loafers'), ('Saappaat', 'Saappaat'), ('Sandaalit', 'Sandaalit'), ('Laukku', 'Laukku'), ('Vyö', 'Vyö'), ('Lippis', 'Lippis'), ('Kaulakoru', 'Kaulakoru'), ('Sormus', 'Sormus'), ('Muu vaate', 'Muu vaate'), ('Dress', 'Dress')], default='Muu vaate', max_length=50),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clothes.category'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='clothes.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='subcategory_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clothes.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_sub_slug_per_cat'),
        ),
    ]
