# Generated by Django 5.2.4 on 2025-08-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_category_alter_clothingitem_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='subcategory',
        ),
    ]
