# Generated by Django 5.2.4 on 2025-08-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_remove_clothingitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='category_ref',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='clothingitem',
            old_name='subcategory_ref',
            new_name='subcategory',
        ),
    ]
